/**
 * FinStack UK - Master Data Architecture & Editorial Dataset
 * Sourced against Trustpilot UK, G2, Capterra, and HMRC compliance guidelines
 */

const AFFILIATE_CONFIG = {
  defaultParam: 'ref=finstack',
  customLinks: {
    tide: 'https://www.tide.co/?ref=YOUR_AFFILIATE_ID',
    'revolut-business': 'https://www.revolut.com/business/?ref=YOUR_AFFILIATE_ID',
    'wise-business': 'https://wise.com/business/?ref=YOUR_AFFILIATE_ID',
    xero: 'https://www.xero.com/uk/?ref=YOUR_AFFILIATE_ID',
    quickbooks: 'https://quickbooks.intuit.com/uk/?ref=YOUR_AFFILIATE_ID'
  }
};

function getAffiliateUrl(toolId, fallbackUrl) {
  if (AFFILIATE_CONFIG.customLinks && AFFILIATE_CONFIG.customLinks[toolId]) {
    return AFFILIATE_CONFIG.customLinks[toolId];
  }
  if (!fallbackUrl) return '#';
  const separator = fallbackUrl.includes('?') ? '&' : '?';
  return `${fallbackUrl}${separator}${AFFILIATE_CONFIG.defaultParam}`;
}

const TOOLS_DATA = [
  {
    id: 'xero',
    name: 'Xero',
    category: 'Accounting',
    tagline: 'Cloud accounting software designed for small businesses and accountants.',
    description: 'Xero provides automated bank feeds, invoicing, VAT return filing (MTD-ready), and payroll integration. Widely supported by UK accountants.',
    editorialTake: 'The gold standard for collaboration with UK chartered accountants. Outstanding app marketplace and reliable HMRC MTD digital return submissions.',
    limitation: 'The entry "Starter" plan limits users to sending just 20 invoices per month, forcing fast-growing micro-businesses onto more expensive plans.',
    whoShouldSkip: 'Sole traders with simple spreadsheet needs who want completely free invoicing without monthly subscriptions.',
    pricing: 'From £15/mo',
    bestFor: 'Sole traders, Small LTDs, Growing businesses',
    features: ['MTD VAT Filing', 'Bank Feeds', 'Invoicing', 'Expense Tracking', 'Multi-currency'],
    tags: ['accounting', 'vat', 'mtd', 'invoicing', 'sole-trader', 'limited-company', 'low-cost'],
    website: 'https://www.xero.com/uk/',
    featured: true,
    rating: 4.1,
    ratingSource: 'Trustpilot UK',
    ratingDate: 'Aug 2026'
  },
  {
    id: 'quickbooks',
    name: 'QuickBooks Online',
    category: 'Accounting',
    tagline: 'Comprehensive accounting tool with strong mileage and tax tracking.',
    description: 'Intuit QuickBooks covers bookkeeping, cash flow forecasting, CIS tracking, and HMRC-recognised Making Tax Digital VAT returns.',
    editorialTake: 'Powerful all-in-one ledger engine especially beneficial for mobile contractors and tradespeople who need automated mileage tracking.',
    limitation: 'Interface can feel complex for first-time non-financial founders; price increases often occur after initial discount periods.',
    whoShouldSkip: 'Founders seeking lightweight, jargon-free accounting without extensive feature clutter.',
    pricing: 'From £10/mo',
    bestFor: 'Contractors, Tradespeople, Small businesses',
    features: ['Mileage Tracker', 'CIS Tracking', 'MTD VAT', 'Automated Reports'],
    tags: ['accounting', 'vat', 'mtd', 'cis', 'sole-trader', 'limited-company'],
    website: 'https://quickbooks.intuit.com/uk/',
    featured: true,
    rating: 3.8,
    ratingSource: 'Trustpilot UK',
    ratingDate: 'Aug 2026'
  },
  {
    id: 'freeagent',
    name: 'FreeAgent',
    category: 'Accounting',
    tagline: 'Intuitive accounting software free for NatWest/RBS business account holders.',
    description: 'Built specifically for UK freelancers and micro-businesses. Direct corporation tax, Self Assessment, and payroll filings straight to HMRC.',
    editorialTake: 'The most stress-free accounting software for solo freelancers. Unbeatable value if you bank with NatWest, RBS, or Mettle since it is included for free.',
    limitation: 'Less flexible for complex inventory management or mid-market companies with complex departmental cost centres.',
    whoShouldSkip: 'Larger limited companies with multi-warehouse inventory or multi-tier approval workflows.',
    pricing: 'From £19/mo (Free with Mettle/NatWest)',
    bestFor: 'Freelancers, Sole traders, Micro LTDs',
    features: ['Self Assessment Filing', 'Corporation Tax', 'Free with banking partners', 'Time Tracking'],
    tags: ['accounting', 'freelance', 'sole-trader', 'limited-company', 'tax', 'free-tier', 'low-cost'],
    website: 'https://www.freeagent.com/',
    featured: true,
    rating: 4.6,
    ratingSource: 'Trustpilot UK',
    ratingDate: 'Aug 2026'
  },
  {
    id: 'sage',
    name: 'Sage Accounting',
    category: 'Accounting',
    tagline: 'Reliable compliance and accounting engine for UK enterprises.',
    description: 'Offers structured financial management, payroll compliance, and multi-entity consolidation for established UK businesses.',
    editorialTake: 'Established UK enterprise compliance bedrock with robust support for complex multi-entity structures and strict audit requirements.',
    limitation: 'UI feels more traditional and less intuitive compared to modern cloud-first challengers.',
    whoShouldSkip: 'Early-stage digital freelancers looking for 1-click mobile-first invoicing.',
    pricing: 'From £14/mo',
    bestFor: 'Established LTDs, Multi-currency operations',
    features: ['Inventory Tracking', 'MTD Compliance', 'Multi-entity support', 'Automated Bank Recs'],
    tags: ['accounting', 'enterprise', 'compliance', 'limited-company', 'vat'],
    website: 'https://www.sage.com/en-gb/',
    featured: false,
    rating: 4.1,
    ratingSource: 'Trustpilot UK',
    ratingDate: 'Aug 2026'
  },
  {
    id: 'clearbooks',
    name: 'Clear Books',
    category: 'Accounting',
    tagline: 'Simple and approachable cloud accounting software for small UK teams.',
    description: 'Clear Books provides easy-to-read financial reports, MTD VAT filing, and automated invoice reminders without complicated jargon.',
    editorialTake: 'Approachable, straightforward cloud ledger built for British micro-businesses wanting hassle-free compliance.',
    limitation: 'Smaller third-party app ecosystem compared to the extensive Xero/QuickBooks marketplaces.',
    whoShouldSkip: 'Fast-scaling tech companies requiring bespoke API connectors and enterprise ERP sync.',
    pricing: 'From £12/mo',
    bestFor: 'Micro businesses, Non-financial founders',
    features: ['Easy Invoicing', 'VAT Submissions', 'Dividend Vouchers', 'CIS Reports'],
    tags: ['accounting', 'vat', 'sole-trader', 'low-cost'],
    website: 'https://www.clearbooks.co.uk/',
    featured: false,
    rating: 4.4,
    ratingSource: 'Trustpilot UK',
    ratingDate: 'Aug 2026'
  },
  {
    id: 'kashflow',
    name: 'KashFlow',
    category: 'Accounting',
    tagline: 'Straightforward bookkeeping and payroll tool built for owner-managed businesses.',
    description: 'Create quotes and invoices on the go, link to payment processors, and file VAT returns smoothly to HMRC.',
    editorialTake: 'Designed for small trade business owners who want simple quotation-to-invoice workflows on mobile devices.',
    limitation: 'User experience has seen fewer major feature refreshes compared to modern competitors.',
    whoShouldSkip: 'Firms with heavy recurring subscription models or multi-currency SaaS billing.',
    pricing: 'From £10.50/mo',
    bestFor: 'Owner-managed trades, Small shops',
    features: ['Quick Quotations', 'VAT Returns', 'Payment Processor Integrations'],
    tags: ['accounting', 'vat', 'sole-trader', 'low-cost'],
    website: 'https://www.kashflow.com/',
    featured: false,
    rating: 3.9,
    ratingSource: 'Trustpilot UK',
    ratingDate: 'Aug 2026'
  },
  {
    id: 'float',
    name: 'Float Cash Flow',
    category: 'Accounting',
    tagline: 'Visual cash flow forecasting software that syncs live with Xero & QuickBooks.',
    description: 'Eliminate manual spreadsheet forecasts by visualizing upcoming cash inflows, bills, and payroll milestones dynamically.',
    editorialTake: 'Outstanding visual scenario planner that helps SME founders map out hiring plans and runway projections.',
    limitation: 'Requires an existing subscription to Xero, QuickBooks, or FreeAgent to function.',
    whoShouldSkip: 'Solo founders with predictable, static overhead who do not require dynamic cash forecasting.',
    pricing: 'From £39/mo',
    bestFor: 'Agencies, Growing companies, CFOs',
    features: ['Live Bank Sync', 'Scenario Planning', 'Runway Forecasts', 'Budgets vs Actuals'],
    tags: ['accounting', 'forecasting', 'teams'],
    website: 'https://floatapp.com/',
    featured: false,
    rating: 4.6,
    ratingSource: 'Xero App Store',
    ratingDate: 'Aug 2026'
  },
  {
    id: 'futuroli',
    name: 'Futrli (by Sage)',
    category: 'Accounting',
    tagline: 'Automated business planning, financial forecasting, and valuation reports.',
    description: 'Generate 3-way financial forecasts, investor-ready pitch deck charts, and balance sheet models connected to your accounts.',
    editorialTake: 'High-grade 3-way financial modeling tool preferred by fractional CFOs and venture-backed UK startups.',
    limitation: 'Steep learning curve for founders without basic double-entry bookkeeping literacy.',
    whoShouldSkip: 'Early-stage sole traders and lifestyle businesses.',
    pricing: 'From £40/mo',
    bestFor: 'Startups raising capital, Fractional CFOs',
    features: ['3-way Forecasting', 'Scenario Modeling', 'Valuation Analysis'],
    tags: ['accounting', 'forecasting', 'startups'],
    website: 'https://www.futrli.com/',
    featured: false,
    rating: 4.3,
    ratingSource: 'G2 Reviews',
    ratingDate: 'Aug 2026'
  },
  {
    id: 'syft-analytics',
    name: 'Syft Analytics',
    category: 'Accounting',
    tagline: 'Management reporting, visualization, and consolidated multi-entity analytics.',
    description: 'Transform complex raw accounting balances into executive dashboards, client reports, and performance scorecards.',
    editorialTake: 'Best-in-class multi-entity consolidation tool that turns raw ledger data into boardroom-ready visual decks.',
    limitation: 'Can be over-engineered for businesses managing a single operating entity.',
    whoShouldSkip: 'Single-person consultancies without multi-department reporting needs.',
    pricing: 'From £15/mo',
    bestFor: 'Accountancy practices, Multi-entity owners',
    features: ['Consolidations', 'Executive Reports', 'Benchmarking', 'White-labeling'],
    tags: ['accounting', 'analytics', 'enterprise'],
    website: 'https://www.syftanalytics.com/',
    featured: false,
    rating: 4.9,
    ratingSource: 'G2 Reviews',
    ratingDate: 'Aug 2026'
  },
  {
    id: 'crunch',
    name: 'Crunch',
    category: 'Accounting',
    tagline: 'Hybrid online accounting software paired with dedicated certified accountants.',
    description: 'All-in-one package providing both intuitive cloud accounting software and on-demand professional accountant support.',
    editorialTake: 'Excellent middle ground for founders who want software convenience paired with a real human accountant to sign off year-end filings.',
    limitation: 'Higher monthly cost than pure standalone software subscriptions.',
    whoShouldSkip: 'Founders who already have an established local external accounting firm.',
    pricing: 'From £24.50/mo',
    bestFor: 'Contractors, Sole traders, Micro-businesses needing human help',
    features: ['Dedicated Accountant Options', 'Year-End Accounts', 'Self Assessment', 'Free Invoicing'],
    tags: ['accounting', 'sole-trader', 'freelance', 'limited-company', 'tax'],
    website: 'https://www.crunch.co.uk/',
    featured: false,
    rating: 4.3,
    ratingSource: 'Trustpilot UK',
    ratingDate: 'Aug 2026'
  },
  {
    id: 'revolut-business',
    name: 'Revolut Business',
    category: 'Business Banking',
    tagline: 'Global business accounts with multi-currency exchange and modern corporate cards.',
    description: 'Enables multi-currency holding accounts, virtual/physical team expense cards, and seamless integration with major accounting tools.',
    editorialTake: 'Unrivalled for international trade and tech companies spending heavily in USD/EUR with near-instant corporate card issuance.',
    limitation: 'Customer service is primarily in-app chat; cash/cheque deposits are not natively supported at high street branches.',
    whoShouldSkip: 'Traditional local retail businesses relying heavily on regular physical cash and coin deposits.',
    pricing: 'Free tier available; Paid from £19/mo',
    bestFor: 'International companies, E-commerce, Startups',
    features: ['Multi-currency FX', 'Corporate Cards', 'API Integration', 'Spend Controls'],
    tags: ['banking', 'international', 'fx', 'cards', 'ecommerce', 'free-tier'],
    website: 'https://www.revolut.com/business/',
    featured: true,
    rating: 4.7,
    ratingSource: 'Trustpilot UK',
    ratingDate: 'Aug 2026'
  },
  {
    id: 'wise-business',
    name: 'Wise Business',
    category: 'Business Banking',
    tagline: 'Cheapest mid-market exchange rate banking alternative for global trade.',
    description: 'Receive international transfers with local account numbers (GBP, EUR, USD) and pay invoices globally without markup.',
    editorialTake: 'The most cost-effective solution for cross-border contractor payouts and receiving multi-currency client retainers at true mid-market FX rates.',
    limitation: 'Not a full UK clearing bank; operates as an authorized Electronic Money Institution (EMI).',
    whoShouldSkip: 'Businesses requiring formal overdraft facilities or UK credit lines directly attached to their current account.',
    pricing: 'One-off setup fee (£45)',
    bestFor: 'Cross-border trade, Freelancers with global clients, Importers/Exporters',
    features: ['Local Bank Details', 'Mid-market FX', 'Batch Payments', 'Accounting Sync'],
    tags: ['banking', 'international', 'fx', 'freelance', 'low-cost'],
    website: 'https://wise.com/gb/business/',
    featured: true,
    rating: 4.3,
    ratingSource: 'Trustpilot UK',
    ratingDate: 'Aug 2026'
  },
  {
    id: 'tide',
    name: 'Tide',
    category: 'Business Banking',
    tagline: 'Fast UK business current accounts with built-in invoicing and company formation.',
    description: 'Open an account in minutes with no credit checks, set up instant sub-accounts for tax savings, and register a new LTD company directly.',
    editorialTake: 'The quickest way in the UK to incorporate a new Limited company and get a working business IBAN within 10 minutes.',
    limitation: 'Transaction fees apply (20p/transfer on free tier); customer funds are held in ring-fenced accounts via ClearBank.',
    whoShouldSkip: 'High-volume transfer businesses that want completely zero-per-transaction fees on entry plans.',
    pricing: 'Free core tier; Paid from £9.99/mo',
    bestFor: 'Sole traders, New startups, Fast account creation',
    features: ['Free Company Registration', 'Auto-categorisation', 'Sub-accounts', 'Instant Invoicing'],
    tags: ['banking', 'sole-trader', 'startups', 'free-tier', 'low-cost'],
    website: 'https://www.tide.co/',
    featured: true,
    rating: 4.4,
    ratingSource: 'Trustpilot UK',
    ratingDate: 'Aug 2026'
  },
  {
    id: 'starling-bank',
    name: 'Starling Bank',
    category: 'Business Banking',
    tagline: 'Award-winning, fully regulated UK digital business bank account with £0 monthly fee.',
    description: 'FSCS-protected banking with 24/7 UK customer support, integrated marketplace, and built-in toolkit for automated bookkeeping.',
    editorialTake: 'The top-rated regulated digital bank in Britain. Full £85,000 FSCS deposit protection, £0 monthly fee, and 24/7 UK support.',
    limitation: 'Strict underwriting criteria during business account onboarding compared to EMI providers.',
    whoShouldSkip: 'High-risk business models or non-UK resident company directors.',
    pricing: 'Free core tier; Business Toolkit £7/mo',
    bestFor: 'UK SMEs, Sole traders, Startups',
    features: ['FSCS Protected', '24/7 Support', 'Zero Monthly Fee', 'Real-time Notifications'],
    tags: ['banking', 'sole-trader', 'limited-company', 'free-tier', 'low-cost'],
    website: 'https://www.starlingbank.com/business-account/',
    featured: true,
    rating: 4.3,
    ratingSource: 'Trustpilot UK',
    ratingDate: 'Aug 2026'
  },
  {
    id: 'monzo-business',
    name: 'Monzo Business',
    category: 'Business Banking',
    tagline: 'Mobile-first banking with automated tax pots and integrated invoicing.',
    description: "Separates tax automatically with 'Tax Pots', syncs directly to Xero/QuickBooks, and provides multi-user access for limited companies.",
    editorialTake: "Exceptional mobile UI for solo founders. The 'Tax Pots' feature automatically sets aside a percentage of income for HMRC whenever you are paid.",
    limitation: 'Pro features like multi-user access and integrated invoicing require the £5/month plan.',
    whoShouldSkip: 'Established mid-sized companies needing complex multi-level corporate approval flows.',
    pricing: 'Free tier; Pro £5/mo',
    bestFor: 'Mobile entrepreneurs, Freelancers, Micro-businesses',
    features: ['Tax Pots', 'Integrated Invoicing', 'Multi-user Access', 'Xero Integration'],
    tags: ['banking', 'tax', 'sole-trader', 'freelance', 'low-cost', 'free-tier'],
    website: 'https://monzo.com/business/',
    featured: false,
    rating: 4.4,
    ratingSource: 'Trustpilot UK',
    ratingDate: 'Aug 2026'
  },
  {
    id: 'ancon',
    name: 'ANNA Money',
    category: 'Business Banking',
    tagline: 'Business account + tax assistant designed for freelancers and micro-businesses.',
    description: 'Combines a debit card with an AI assistant that calculates your tax liability in real time, creates invoices, and chases payments.',
    editorialTake: 'Clever chat-driven business account that handles invoice chasing and estimates your tax bill on the fly.',
    limitation: 'Pay-as-you-go pricing adds small fees for every payout if you do not subscribe to a paid monthly plan.',
    whoShouldSkip: 'Companies with their own dedicated in-house finance staff.',
    pricing: 'Free pay-as-you-go or £14.90/mo',
    bestFor: 'Creative freelancers, Solo entrepreneurs',
    features: ['Real-time Tax Calculations', 'Automated Invoicing', 'Chat-based Support'],
    tags: ['banking', 'sole-trader', 'freelance', 'tax', 'low-cost'],
    website: 'https://anna.money/',
    featured: false,
    rating: 4.6,
    ratingSource: 'Trustpilot UK',
    ratingDate: 'Aug 2026'
  },
  {
    id: 'mettle',
    name: 'Mettle by NatWest',
    category: 'Business Banking',
    tagline: 'Free digital business account with built-in invoice creation and free FreeAgent access.',
    description: 'Includes free FreeAgent accounting subscription, automatic tax holdback calculation, and zero monthly fees.',
    editorialTake: 'One of the best value propositions for sole traders because it includes FreeAgent accounting completely free of charge.',
    limitation: 'Max account balance caps apply; no international SWIFT/IBAN payments incoming.',
    whoShouldSkip: 'Exporters and businesses receiving regular international foreign currency wires.',
    pricing: '£0 Free',
    bestFor: 'Sole traders, Early-stage Limited companies',
    features: ['Includes FreeAgent ($300+ value)', 'Tax Pots', 'Quick Invoicing', 'UK Support'],
    tags: ['banking', 'accounting', 'sole-trader', 'limited-company', 'free-tier', 'low-cost'],
    website: 'https://www.mettle.co.uk/',
    featured: true,
    rating: 4.5,
    ratingSource: 'Trustpilot UK',
    ratingDate: 'Aug 2026'
  },
  {
    id: 'stripe',
    name: 'Stripe',
    category: 'Payments',
    tagline: 'The developer standard payment gateway for global online commerce.',
    description: 'Accept credit cards, mobile wallets, recurring subscriptions, and localized payment methods across web and mobile apps.',
    editorialTake: 'The global gold standard for SaaS, digital checkouts, and custom API billing with unmatched documentation.',
    limitation: 'Higher processing fees on cross-border cards; strict dispute holdback policies for new high-volume merchants.',
    whoShouldSkip: 'Brick-and-mortar merchants wanting exclusively cheap physical counter card terminals.',
    pricing: '1.5% + 20p for standard UK cards',
    bestFor: 'SaaS, E-commerce, Tech startups',
    features: ['Subscription Billing', 'Fraud Prevention (Radar)', 'Global Payments', 'Custom Checkout'],
    tags: ['payments', 'ecommerce', 'saas', 'subscriptions', 'developer'],
    website: 'https://stripe.com/gb',
    featured: true,
    rating: 4.3,
    ratingSource: 'G2 Reviews',
    ratingDate: 'Aug 2026'
  },
  {
    id: 'gocardless',
    name: 'GoCardless',
    category: 'Payments',
    tagline: 'Direct Debit payment solution optimized for recurring retainer and invoice collection.',
    description: 'Drastically reduce payment churn and processing fees by collecting recurring bank-to-bank payments directly from customer accounts.',
    editorialTake: 'Essential for UK B2B agencies and accountancies. Eliminates credit card failure rates by pulling funds via automated Direct Debit.',
    limitation: 'Funds take 3–5 working days to settle into your bank account compared to instant card payouts.',
    whoShouldSkip: 'E-commerce shops needing instant 1-second checkout for physical goods.',
    pricing: '1% + 20p per transaction (capped)',
    bestFor: 'B2B agencies, Subscription businesses, Accountancy firms',
    features: ['Direct Debit', 'Instant Bank Pay (Open Banking)', 'Low Transaction Fees', 'Auto Reconciliation'],
    tags: ['payments', 'subscriptions', 'b2b', 'low-cost'],
    website: 'https://gocardless.com/',
    featured: true,
    rating: 4.3,
    ratingSource: 'G2 Reviews',
    ratingDate: 'Aug 2026'
  },
  {
    id: 'sumup',
    name: 'SumUp',
    category: 'Payments',
    tagline: 'Affordable POS card readers and payment terminals for in-person transactions.',
    description: 'No monthly fixed fees, simple pocket card terminals, and rapid payouts for pop-up shops, market vendors, and tradespeople.',
    editorialTake: 'Zero monthly contract commitment makes this ideal for popups, weekend markets, and mobile field trades.',
    limitation: 'Transaction fee of 1.69% is higher than traditional multi-year merchant acquiring contracts on high volume.',
    whoShouldSkip: 'High-volume retail stores turning over >£20,000/month in counter sales.',
    pricing: '1.69% per in-person transaction; No monthly fee',
    bestFor: 'Retail, Cafes, Mobile services, Trades',
    features: ['No Monthly Contracts', 'Pocket Terminals', 'Virtual Invoices', 'Quick Setup'],
    tags: ['payments', 'pos', 'retail', 'sole-trader', 'low-cost'],
    website: 'https://www.sumup.com/en-gb/',
    featured: false,
    rating: 4.2,
    ratingSource: 'Trustpilot UK',
    ratingDate: 'Aug 2026'
  },
  {
    id: 'zettle',
    name: 'Zettle by PayPal',
    category: 'Payments',
    tagline: 'Comprehensive point-of-sale hardware and inventory management for physical stores.',
    description: 'Fast-loading mobile checkout, hardware bundles, and inventory synchronization with seamless PayPal settlement.',
    editorialTake: 'Polished POS hardware and software bundle with seamless inventory synchronization for boutique retail and coffee shops.',
    limitation: '1.75% transaction fee; tied directly to the PayPal ecosystem.',
    whoShouldSkip: 'Pure digital businesses without an in-person physical sales presence.',
    pricing: '1.75% per card transaction',
    bestFor: 'Hospitality, Brick-and-mortar retail, Event stalls',
    features: ['POS Software', 'Inventory Sync', 'Barcode Scanning', 'Daily Payouts'],
    tags: ['payments', 'pos', 'retail', 'hospitality'],
    website: 'https://www.zettle.com/gb',
    featured: false,
    rating: 3.8,
    ratingSource: 'Trustpilot UK',
    ratingDate: 'Aug 2026'
  },
  {
    id: 'square',
    name: 'Square UK',
    category: 'Payments',
    tagline: 'Omnichannel checkout, point-of-sale software, and contactless hardware.',
    description: 'Accept in-person, online, and over-the-phone payments with flat transparent rates, free software, and fast next-day payouts.',
    editorialTake: 'The premier omnichannel platform connecting in-person shop registers with an online digital storefront in one unified backend.',
    limitation: 'Higher flat rate percentage for manually keyed-in over-the-phone virtual terminal payments.',
    whoShouldSkip: 'Enterprises needing deeply bespoke ERP hardware integration.',
    pricing: '1.75% in-person, 1.4% + 25p online',
    bestFor: 'Omnichannel retail, Popups, Beauty salons',
    features: ['Free POS App', 'Hardware Ecosystem', 'Online Store Builder', 'Next-day Transfers'],
    tags: ['payments', 'pos', 'retail', 'ecommerce', 'low-cost'],
    website: 'https://squareup.com/gb/en',
    featured: false,
    rating: 4.2,
    ratingSource: 'Trustpilot UK',
    ratingDate: 'Aug 2026'
  },
  {
    id: 'mollie',
    name: 'Mollie',
    category: 'Payments',
    tagline: 'Effortless European and UK payment processing for e-commerce platforms.',
    description: 'Simple plugin-based checkout for WooCommerce, Shopify, and custom apps supporting Apple Pay, Klarna, and cards.',
    editorialTake: 'Transparent European payment gateway offering swift plugin setup for WooCommerce, Magento, and Shopify store owners.',
    limitation: 'Smaller developer tooling community compared to Stripe’s extensive SDK library.',
    whoShouldSkip: 'Complex multi-sided marketplace platforms requiring custom escrow payouts.',
    pricing: 'Pay per transaction: 1.2% + 20p',
    bestFor: 'E-commerce merchants, Web shops',
    features: ['Easy CMS Plugins', 'No Monthly Fees', 'Transparent Pricing', 'Fast Checkout'],
    tags: ['payments', 'ecommerce', 'low-cost'],
    website: 'https://www.mollie.com/gb',
    featured: false,
    rating: 4.4,
    ratingSource: 'Trustpilot UK',
    ratingDate: 'Aug 2026'
  },
  {
    id: 'chaser',
    name: 'Chaser',
    category: 'Payments',
    tagline: 'Automated invoice chasing and accounts receivable debtor management software.',
    description: 'Politely prompt clients to pay late invoices via automated customized email/SMS reminders, reducing DSO significantly.',
    editorialTake: 'Proven cash flow accelerator for UK consultancies that significantly cuts down overdue debtor days without damaging client relationships.',
    limitation: 'Monthly subscription cost means you need sufficient unpaid invoice volume to justify the software ROI.',
    whoShouldSkip: 'B2C retail or businesses that take immediate upfront card payments.',
    pricing: 'From £40/mo',
    bestFor: 'B2B businesses, Agencies with late-paying clients',
    features: ['Automated Reminders', 'Payment Portal', 'Credit Checking', 'Debtor Tracking'],
    tags: ['payments', 'invoicing', 'automation', 'b2b'],
    website: 'https://www.chaserhq.com/',
    featured: false,
    rating: 4.8,
    ratingSource: 'Xero App Store',
    ratingDate: 'Aug 2026'
  },
  {
    id: 'dext',
    name: 'Dext Prepare',
    category: 'Expenses',
    tagline: 'Automated receipt capture and paperwork extraction for zero-data-entry bookkeeping.',
    description: 'Snap receipts on mobile or auto-forward digital bills. Extracts line items, VAT, and supplier info directly to your accounting tool.',
    editorialTake: 'The most accurate OCR engine in the UK market for parsing fuel receipts, supplier invoices, and messy paperwork directly into Xero.',
    limitation: 'Pricing is based on monthly receipt document limits which can scale quickly if unmonitored.',
    whoShouldSkip: 'Sole traders with under 5 supplier expense receipts per month.',
    pricing: 'From £27/mo',
    bestFor: 'SMEs with high invoice volume, Accountants, Bookkeepers',
    features: ['OCR Receipt Extraction', 'Approval Workflows', 'Line-item Detail', 'Audit-ready Cloud Vault'],
    tags: ['expenses', 'vat', 'receipts', 'automation', 'compliance'],
    website: 'https://dext.com/uk',
    featured: true,
    rating: 4.7,
    ratingSource: 'Trustpilot UK',
    ratingDate: 'Aug 2026'
  },
  {
    id: 'pleo',
    name: 'Pleo',
    category: 'Expenses',
    tagline: 'Smart company cards paired with automated real-time expense reporting.',
    description: 'Distribute prepaid Mastercard smart cards to staff with custom spending limits, instant receipt capture prompts, and zero mileage paperwork.',
    editorialTake: 'Eliminates monthly employee expense claim spreadsheets. When staff swipe their Pleo card, an instant notification prompts them to snap the receipt.',
    limitation: 'Card balance requires pre-funding via bank transfer unless you qualify for overdraft credit tiers.',
    whoShouldSkip: 'Single-person businesses with no team members or staff expense cards.',
    pricing: 'Free plan available; Paid from £39/mo',
    bestFor: 'Growing teams (5-100 employees), Tech firms, Agencies',
    features: ['Individual Spending Limits', 'Instant Receipt Alerts', 'Mileage Tracking', 'Accounting Integration'],
    tags: ['expenses', 'cards', 'limited-company', 'teams'],
    website: 'https://www.pleo.io/en-gb',
    featured: true,
    rating: 3.8,
    ratingSource: 'Trustpilot UK',
    ratingDate: 'Aug 2026'
  },
  {
    id: 'soldo',
    name: 'Soldo',
    category: 'Expenses',
    tagline: 'Prepaid business cards with centralized multi-user expense control architecture.',
    description: 'Provides granular spending rules, multi-currency wallets, and company-wide budget delegation for operations teams.',
    editorialTake: 'Granular multi-user expense architecture that gives finance directors tight department-level card spending rules.',
    limitation: 'Monthly platform fees scale rapidly as team card headcount increases.',
    whoShouldSkip: 'Early-stage micro-teams seeking basic free expense tracking.',
    pricing: 'From £30/mo',
    bestFor: 'Mid-sized UK businesses, Multi-department teams',
    features: ['Multi-currency Wallets', 'Granular Budgets', 'Approval Flow', 'Custom Rules'],
    tags: ['expenses', 'cards', 'enterprise', 'teams'],
    website: 'https://www.soldo.com/en-gb/',
    featured: false,
    rating: 4.4,
    ratingSource: 'Trustpilot UK',
    ratingDate: 'Aug 2026'
  },
  {
    id: 'expensify',
    name: 'Expensify',
    category: 'Expenses',
    tagline: 'Receipt scanning, corporate travel management, and personal expense reimbursements.',
    description: 'One-click receipt scanning (SmartScan), corporate card tracking, and automatic reimbursement through direct bank transfers.',
    editorialTake: 'Established global expense management standard with robust features for multi-city corporate travel and employee mileage tracking.',
    limitation: 'Frequent billing model adjustments have drawn critique from smaller SMB users.',
    whoShouldSkip: 'UK businesses needing direct, simple MTD-focused bookkeeping without travel booking add-ons.',
    pricing: 'From £4.50/user/mo',
    bestFor: 'Remote teams, Traveling staff, Consultancies',
    features: ['SmartScan OCR', 'Next-day Reimbursements', 'Travel Booking', 'Multi-level Approvals'],
    tags: ['expenses', 'receipts', 'travel', 'teams'],
    website: 'https://use.expensify.com/',
    featured: false,
    rating: 4.4,
    ratingSource: 'G2 Reviews',
    ratingDate: 'Aug 2026'
  },
  {
    id: 'moss',
    name: 'Moss',
    category: 'Expenses',
    tagline: 'True credit card solutions and holistic spend management for fast-growth firms.',
    description: 'Issue physical/virtual cards with high credit limits, automate invoice matching, and manage corporate spend policies seamlessly.',
    editorialTake: 'True corporate credit cards paired with comprehensive invoice approval pipelines for fast-scaling startups.',
    limitation: 'Higher entry eligibility thresholds tailored for established scaleups rather than early micro-businesses.',
    whoShouldSkip: 'Unfunded early-stage founders or solo practitioners.',
    pricing: 'Custom pricing',
    bestFor: 'Scaleups, Mid-market enterprises',
    features: ['High Credit Lines', 'Invoice Approvals', 'ERP Sync', 'Real-time Audits'],
    tags: ['expenses', 'cards', 'enterprise', 'teams'],
    website: 'https://getmoss.com/en-gb/',
    featured: false,
    rating: 4.6,
    ratingSource: 'Trustpilot UK',
    ratingDate: 'Aug 2026'
  },
  {
    id: 'spendesk',
    name: 'Spendesk',
    category: 'Expenses',
    tagline: '7-in-1 spend management platform covering corporate cards, invoices, and budgets.',
    description: 'Total visibility on company spending: employee cards, invoice processing, expense reimbursements, and automated accounting sync.',
    editorialTake: 'High-end corporate spend platform offering total visibility over purchase orders, team debit cards, and invoice approvals.',
    limitation: 'Pricing is quote-based and prohibitive for companies with fewer than 15 employees.',
    whoShouldSkip: 'Small teams and lifestyle agencies.',
    pricing: 'Custom tier',
    bestFor: 'Mid-sized companies, Finance directors',
    features: ['Pre-approvals', 'Purchase Orders', 'Virtual Mastercards', 'Auto VAT Detection'],
    tags: ['expenses', 'cards', 'teams', 'enterprise'],
    website: 'https://www.spendesk.com/en-gb/',
    featured: false,
    rating: 4.5,
    ratingSource: 'G2 Reviews',
    ratingDate: 'Aug 2026'
  },
  {
    id: 'autoentry',
    name: 'AutoEntry',
    category: 'Expenses',
    tagline: 'Intelligent document scanning for receipts, bills, and paper bank statements.',
    description: 'Convert paper receipts, purchase orders, and scanned bank statements directly into organized data ready for ledger import.',
    editorialTake: 'The most cost-flexible document extraction tool for bookkeepers due to its credit-based pay-as-you-go structure.',
    limitation: 'Interface is utility-driven and less modern than Dext, though functionally very solid.',
    whoShouldSkip: 'Founders who want a glossy mobile app experience rather than a high-volume desktop processing queue.',
    pricing: 'Pay-as-you-go credit system',
    bestFor: 'Bookkeepers, In-house accountants',
    features: ['Bank Statement OCR', 'Line Item Extraction', 'Cross-accounting Sync'],
    tags: ['expenses', 'receipts', 'automation', 'low-cost'],
    website: 'https://www.autoentry.com/',
    featured: false,
    rating: 4.4,
    ratingSource: 'Trustpilot UK',
    ratingDate: 'Aug 2026'
  },
  {
    id: 'brightpay',
    name: 'BrightPay',
    category: 'Payroll',
    tagline: 'Desktop and cloud UK payroll software handling RTI, Auto-enrolment, and CIS.',
    description: 'Fully compliant payroll solution built for the UK market with direct HMRC RTI submission and automatic workplace pension communication.',
    editorialTake: 'Widely regarded by UK payroll managers as the most dependable, fully compliant payroll platform for statutory leave and workplace pensions.',
    limitation: 'Historical desktop heritage means cloud-only multi-admin workflows are still evolving across their cloud tier.',
    whoShouldSkip: 'Solo founders with no salaried employees or workplace pension obligations.',
    pricing: 'From £109/year',
    bestFor: 'In-house payroll teams, Small businesses with employees',
    features: ['HMRC RTI Submissions', 'Auto-enrolment Pensions', 'CIS Calculations', 'Employee Self-service Portal'],
    tags: ['payroll', 'pensions', 'cis', 'compliance', 'limited-company'],
    website: 'https://www.brightpay.co.uk/',
    featured: false,
    rating: 4.7,
    ratingSource: 'Trustpilot UK',
    ratingDate: 'Aug 2026'
  },
  {
    id: 'employment-hero',
    name: 'Employment Hero Payroll',
    category: 'Payroll',
    tagline: 'Automated cloud payroll and all-in-one HR system for scaling businesses.',
    description: 'Combines time-sheeting, roster planning, auto-pay runs, and statutory leave calculations in an integrated employee app.',
    editorialTake: 'Excellent all-in-one payroll and HR suite for shift-based businesses, hospitality, and growing teams.',
    limitation: 'Can feel overly comprehensive if you only need simple monthly direct payroll runs without HR modules.',
    whoShouldSkip: 'Micro-businesses with 1–2 fixed salary directors.',
    pricing: 'From £5/employee/mo',
    bestFor: 'Growing SMEs, Shift-based companies, Remote teams',
    features: ['Shift Scheduling', 'Automated Timesheets', 'RTI Submissions', 'Pension Integrations'],
    tags: ['payroll', 'hr', 'teams', 'compliance'],
    website: 'https://employmenthero.com/uk/payroll/',
    featured: false,
    rating: 4.5,
    ratingSource: 'G2 Reviews',
    ratingDate: 'Aug 2026'
  },
  {
    id: 'payfit',
    name: 'PayFit',
    category: 'Payroll',
    tagline: 'Automated payroll management with intuitive employee portal and HR tools.',
    description: 'Simplifies UK payroll runs, payslips, leaves, expenses, and HMRC compliance with minimal manual input required.',
    editorialTake: 'The most modern, automated payroll experience in the UK for tech startups and remote-friendly companies.',
    limitation: 'Custom pricing is geared towards growing tech companies rather than budget-conscious micro-trades.',
    whoShouldSkip: 'Sole practitioners looking for budget-entry desktop payroll.',
    pricing: 'Custom pricing based on headcount',
    bestFor: 'Scaleups, Modern SMEs, Tech businesses',
    features: ['Automatic Payslips', 'HRIS Integration', 'HMRC RTI & Pensions', 'Direct BACS Payments'],
    tags: ['payroll', 'hr', 'automation', 'scaleups'],
    website: 'https://payfit.com/gb/',
    featured: true,
    rating: 4.4,
    ratingSource: 'Trustpilot UK',
    ratingDate: 'Aug 2026'
  },
  {
    id: 'nest-pensions',
    name: 'Nest Pensions',
    category: 'Tax & Compliance',
    tagline: 'Government-established workplace pension scheme for UK employer auto-enrolment.',
    description: 'Free for employers to set up and guaranteed to accept any UK employer seeking compliance with auto-enrolment laws.',
    editorialTake: 'The essential safety net for UK employers. Free for employers to set up with statutory guaranteed acceptance for all staff auto-enrolment.',
    limitation: 'Annual contribution management charges apply directly to employee pension pots.',
    whoShouldSkip: 'Companies seeking high-end bespoke salary sacrifice executive pension schemes.',
    pricing: 'Free for employers; 0.3% annual member fee',
    bestFor: 'Small employers, New LTDs hiring first staff',
    features: ['Guaranteed Acceptance', 'HMRC/TPR Compliant', 'Payroll Integration', 'Ethical Fund Options'],
    tags: ['compliance', 'tax', 'pensions', 'free-tier', 'limited-company'],
    website: 'https://www.nestpensions.org.uk/',
    featured: false,
    rating: 4.1,
    ratingSource: 'Trustpilot UK',
    ratingDate: 'Aug 2026'
  },
  {
    id: 'capdesk',
    name: 'Capdesk (by Carta)',
    category: 'Tax & Compliance',
    tagline: 'Equity management and digital cap table software for UK startups.',
    description: 'Issue employee share options (EMI schemes), track investor ownership, and automate legal equity filings for British startups.',
    editorialTake: 'The UK market leader for setting up HMRC-approved Enterprise Management Incentive (EMI) employee share option schemes.',
    limitation: 'High price point intended for venture-backed and high-growth equity companies.',
    whoShouldSkip: 'Standard 100%-owner Limited Companies with no external investors or employee option pools.',
    pricing: 'Quote-based plans',
    bestFor: 'Funded startups, Scaleups, High-growth LTDs',
    features: ['EMI Option Schemes', 'Cap Table Modelling', 'Investor Portals', 'Companies House Sync'],
    tags: ['compliance', 'tax', 'equity', 'startups', 'scaleups'],
    website: 'https://capdesk.com/',
    featured: false,
    rating: 4.6,
    ratingSource: 'G2 Reviews',
    ratingDate: 'Aug 2026'
  },
  {
    id: 'taxfiler',
    name: 'Taxfiler (by IRIS)',
    category: 'Tax & Compliance',
    tagline: 'Cloud-based tax return and financial statement preparation software.',
    description: 'File Corporation Tax (CT600), Self Assessment (SA100), Partnership returns, and iXBRL accounts directly to HMRC and Companies House.',
    editorialTake: 'Affordable and trusted tax compliance software for preparing statutory CT600 accounts and direct HMRC electronic filings.',
    limitation: 'Designed with accounting tax practitioners in mind rather than lay non-accountant business owners.',
    whoShouldSkip: 'Founders who want their external accountant to prepare and file all statutory year-end accounts.',
    pricing: 'From £15/mo',
    bestFor: 'Accountants, Bookkeepers, Property investors',
    features: ['CT600 Filing', 'Companies House Accounts', 'iXBRL Tagging', 'Self Assessment'],
    tags: ['compliance', 'tax', 'accounting', 'sole-trader', 'limited-company'],
    website: 'https://taxfiler.co.uk/',
    featured: false,
    rating: 4.5,
    ratingSource: 'Capterra UK',
    ratingDate: 'Aug 2026'
  },
  {
    id: 'chargebee',
    name: 'Chargebee',
    category: 'Billing',
    tagline: 'Subscription billing and revenue management platform for SaaS companies.',
    description: 'Automate recurring billing, UK/EU VAT compliance on digital goods, churn recovery, and multi-currency renewals.',
    editorialTake: 'Comprehensive recurring revenue and subscription billing engine with out-of-the-box handling of UK/EU digital VAT rules.',
    limitation: 'Substantial price jump once you exceed free sandbox tier revenue limits.',
    whoShouldSkip: 'B2B agencies sending simple manual invoices once a month.',
    pricing: 'Free launch tier; Paid from $599/mo',
    bestFor: 'SaaS founders, Digital product creators',
    features: ['Automated Invoicing', 'VAT MOSS Compliance', 'Dunning Engine', 'CRM Sync'],
    tags: ['billing', 'payments', 'subscriptions', 'saas', 'vat'],
    website: 'https://www.chargebee.com/',
    featured: false,
    rating: 4.4,
    ratingSource: 'G2 Reviews',
    ratingDate: 'Aug 2026'
  },
  {
    id: 'iwoca',
    name: 'iwoca',
    category: 'Lending',
    tagline: 'Fast, flexible working capital and credit lines for UK small businesses.',
    description: 'Apply for revolving business credit facilities up to £500,000 with rapid online decisions based on live bank data.',
    editorialTake: 'Rapid working capital lines that link directly to your business account via Open Banking for decisions within hours.',
    limitation: 'Interest rates on revolving credit are higher than traditional secured high-street bank commercial loans.',
    whoShouldSkip: 'Businesses seeking long-term 10-year fixed commercial property mortgages.',
    pricing: 'Interest rates vary based on usage',
    bestFor: 'Seasonal businesses, Working capital, Inventory purchases',
    features: ['Revolving Credit', 'Instant Decisions', 'No Early Repayment Fees', 'Open Banking Integration'],
    tags: ['lending', 'banking', 'loans', 'startups', 'limited-company'],
    website: 'https://www.iwoca.co.uk/',
    featured: true,
    rating: 4.7,
    ratingSource: 'Trustpilot UK',
    ratingDate: 'Aug 2026'
  },
  {
    id: 'funding-circle',
    name: 'Funding Circle',
    category: 'Lending',
    tagline: 'UK government-accredited small business loans and commercial financing.',
    description: 'Unsecured business loans from £10,000 to £500,000 with flexible fixed repayment terms and competitive rates.',
    editorialTake: 'The premier UK marketplace lender for established trading SMEs looking for structured, multi-year expansion capital.',
    limitation: 'Requires established trading history (minimum 1–2 years filed accounts) to secure favorable rate tiers.',
    whoShouldSkip: 'Brand new day-one pre-revenue startups.',
    pricing: 'Competitive interest + arrangement fee',
    bestFor: 'Established UK businesses looking to expand',
    features: ['Unsecured Loans', 'Fast Decisions', 'Fixed Repayments'],
    tags: ['lending', 'banking', 'loans', 'enterprise'],
    website: 'https://www.fundingcircle.com/uk/',
    featured: false,
    rating: 4.5,
    ratingSource: 'Trustpilot UK',
    ratingDate: 'Aug 2026'
  },
  {
    id: 'capital-on-tap',
    name: 'Capital on Tap',
    category: 'Lending',
    tagline: 'Business credit cards with up to 1% uncapped cashback and credit lines up to £250k.',
    description: 'Credit card designed exclusively for UK limited companies with no foreign transaction fees and seamless accounting sync.',
    editorialTake: 'One of the most practical credit cards for UK Limited companies with uncapped cashback on ad spend and 0% foreign FX fees.',
    limitation: 'Available exclusively to incorporated UK Limited companies (not available to unregistered sole traders).',
    whoShouldSkip: 'Sole traders operating under their personal legal name without an incorporated LTD entity.',
    pricing: 'Free standard card or £99/yr Rewards',
    bestFor: 'UK Limited Companies, High ad-spend companies',
    features: ['Uncapped Cashback', '0% Foreign FX Fees', 'Integrations with Xero/FreeAgent', 'Up to £250k limits'],
    tags: ['lending', 'banking', 'cards', 'limited-company', 'fx'],
    website: 'https://www.capitalontap.com/en/',
    featured: false,
    rating: 4.6,
    ratingSource: 'Trustpilot UK',
    ratingDate: 'Aug 2026'
  }
];

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { TOOLS_DATA, AFFILIATE_CONFIG, getAffiliateUrl };
}
